package filesize

import (
	"context"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestCheckerPhysicalLineBoundaries(t *testing.T) {
	cases := []struct {
		name, path string
		lines      int
		warnings   int
		denied     bool
	}{
		{"production_499", "internal/example.go", 499, 0, false},
		{"production_500", "internal/example.go", 500, 0, false},
		{"production_501", "internal/example.go", 501, 1, false},
		{"production_800", "internal/example.go", 800, 1, false},
		{"production_801", "internal/example.go", 801, 0, true},
		{"other_500", "docs/example.md", 500, 0, false},
		{"other_501", "docs/example.md", 501, 1, false},
		{"other_800", "docs/example.md", 800, 1, false},
		{"other_801", "docs/example.md", 801, 1, false},
		{"script_299", "scripts/example.sh", 299, 0, false},
		{"script_300", "scripts/example.sh", 300, 0, false},
		{"script_301", "scripts/example.sh", 301, 0, true},
	}
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			report, err := runMemoryCheck(t, map[string][]byte{test.path: lineData(test.lines)}, validPolicy(), "2026-08-19")
			if test.denied {
				requireCode(t, err, CodeDenied)
				if report.Counts.Denials != 1 || report.Outcome != "denied" {
					t.Fatalf("denial report = %+v", report)
				}
				return
			}
			requirePassed(t, report, err)
			if report.Counts.Warnings != test.warnings {
				t.Fatalf("warnings=%d, want %d", report.Counts.Warnings, test.warnings)
			}
		})
	}
}

func TestPhysicalLineEncodingCases(t *testing.T) {
	for name, data := range map[string][]byte{
		"empty": nil, "no_final_newline": []byte("one"), "crlf": []byte("one\r\ntwo\r\n"),
		"huge_line": []byte(strings.Repeat("x", 1<<20)),
	} {
		t.Run(name, func(t *testing.T) {
			report, err := runMemoryCheck(t, map[string][]byte{"docs/input.txt": data}, validPolicy(), "2026-08-19")
			requirePassed(t, report, err)
		})
	}
	if physicalLines([]byte("one")) != 1 || physicalLines([]byte("one\r\ntwo\r\n")) != 2 || physicalLines(nil) != 0 {
		t.Fatal("physical line counter does not implement the locked EOF/CRLF contract")
	}
}

func TestPhysicalLineThresholdsAcrossEOFAndCRLF(t *testing.T) {
	type boundary struct {
		path     string
		lines    int
		warnings int
		denied   bool
	}
	boundaries := []boundary{
		{"scripts/input.sh", 299, 0, false}, {"scripts/input.sh", 300, 0, false}, {"scripts/input.sh", 301, 0, true},
		{"docs/input.md", 499, 0, false}, {"docs/input.md", 500, 0, false}, {"docs/input.md", 501, 1, false},
		{"docs/input.md", 800, 1, false}, {"docs/input.md", 801, 1, false},
	}
	encodings := map[string]func(int) []byte{
		"lf_final": lineData,
		"no_final_lf": func(lines int) []byte {
			if lines == 0 {
				return nil
			}
			return []byte(strings.Repeat("x\n", lines-1) + "x")
		},
		"crlf": func(lines int) []byte { return []byte(strings.Repeat("x\r\n", lines)) },
	}
	for encoding, encode := range encodings {
		for _, test := range boundaries {
			name := encoding + "_" + strings.ReplaceAll(test.path, "/", "_") + "_" + decimal(test.lines)
			t.Run(name, func(t *testing.T) {
				report, err := runMemoryCheck(t, map[string][]byte{test.path: encode(test.lines)}, validPolicy(), "2026-08-19")
				if test.denied {
					requireCode(t, err, CodeDenied)
				} else {
					requirePassed(t, report, err)
				}
				if report.Counts.Warnings != test.warnings || physicalLines(encode(test.lines)) != test.lines {
					t.Fatalf("report=%+v physicalLines=%d", report.Counts, physicalLines(encode(test.lines)))
				}
			})
		}
	}
}

func TestGeneratedHeaderFormsAndFirstFiveLineBoundary(t *testing.T) {
	for position := 1; position <= 6; position++ {
		data := []byte(strings.Repeat("ordinary\n", position-1) + "// Code generated by tool; DO NOT EDIT.\n")
		if got := generatedHeader(data, "tool"); got != (position <= 5) {
			t.Fatalf("position %d accepted=%t", position, got)
		}
	}
	for name, line := range map[string]string{
		"slash":        "// Code generated by tool; DO NOT EDIT.",
		"hash":         "# Code generated by tool; DO NOT EDIT.",
		"sql":          "-- Code generated by tool; DO NOT EDIT.",
		"block":        "/* Code generated by tool; DO NOT EDIT. */",
		"block_middle": "* Code generated by tool; DO NOT EDIT.",
		"json":         `"$comment": "Code generated by tool; DO NOT EDIT.",`,
	} {
		t.Run(name, func(t *testing.T) {
			if !generatedHeader([]byte(line+"\n"), "tool") {
				t.Fatalf("supported header form rejected: %q", line)
			}
		})
	}
	for name, data := range map[string][]byte{
		"mismatch": []byte("// Code generated by other; DO NOT EDIT.\n"),
		"missing":  []byte("// ordinary comment\n"),
		"late":     []byte("1\n2\n3\n4\n5\n// Code generated by tool; DO NOT EDIT.\n"),
	} {
		if generatedHeader(data, "tool") {
			t.Fatalf("%s invalid header accepted", name)
		}
	}
}

func TestCheckerRequiresExceptionsForGovernedAssetsAboveHardLimit(t *testing.T) {
	for name, fixture := range map[string]struct {
		path string
		data []byte
	}{
		"vendor":           {"vendor/library.txt", lineData(801)},
		"third party":      {"third_party/library.txt", lineData(801)},
		"schema suffix":    {"contracts/large.schema.json", lineData(801)},
		"schema directory": {"contracts/schemas/large.json", lineData(801)},
		"migration data":   {"db/migration_data/large.json", lineData(801)},
		"fixture":          {"contracts/fixtures/large.json", lineData(801)},
		"testdata":         {"internal/testdata/large.txt", lineData(801)},
		"generated marker": {"assets/generated.txt", headerData(801, "# ", "coh-test-generator")},
	} {
		t.Run(name, func(t *testing.T) {
			report, err := runMemoryCheck(t, map[string][]byte{fixture.path: fixture.data}, validPolicy(), "2026-08-19")
			requireCode(t, err, CodeDenied)
			if len(report.Findings) != 1 || report.Findings[0].Reason != "governed_asset_hard_limit" {
				t.Fatalf("findings=%+v", report.Findings)
			}
		})
	}
	prose := []byte("This guide quotes Code generated by tool; DO NOT EDIT. as an example.\n" + strings.Repeat("x\n", 800))
	report, err := runMemoryCheck(t, map[string][]byte{"docs/prose.md": prose}, validPolicy(), "2026-08-19")
	requirePassed(t, report, err)
	if report.Counts.Warnings != 1 || report.Counts.Denials != 0 {
		t.Fatalf("ordinary prose was classified as generated: %+v", report)
	}
}

func TestCheckerBinaryClassification(t *testing.T) {
	for _, path := range []string{"internal/binary.go", "scripts/binary.sh"} {
		report, err := runMemoryCheck(t, map[string][]byte{path: {0xff, 0x00}}, validPolicy(), "2026-08-19")
		requireCode(t, err, CodeDenied)
		if report.Findings[0].Reason != "classified_binary_input" {
			t.Fatalf("reason=%q", report.Findings[0].Reason)
		}
	}
	report, err := runMemoryCheck(t, map[string][]byte{"assets/image.bin": {0xff, 0x00}}, validPolicy(), "2026-08-19")
	requirePassed(t, report, err)
	if report.Counts.Skipped != 1 {
		t.Fatalf("skipped=%d", report.Counts.Skipped)
	}
}

func TestCheckerScriptClassificationPrecedence(t *testing.T) {
	cases := map[string]memoryFile{
		"scripts/name.txt":             {data: lineData(301), mode: 0o644},
		".github/workflows/gate.yml":   {data: lineData(301), mode: 0o644},
		"db/migrations/001.data":       {data: lineData(301), mode: 0o644},
		"build/Dockerfile.generated":   {data: lineData(301), mode: 0o644},
		"build/Makefile":               {data: lineData(301), mode: 0o644},
		"build/Taskfile.generated.yml": {data: lineData(301), mode: 0o644},
		"bin/tool":                     {data: append([]byte("#!/bin/bash\n"), lineData(300)...), mode: 0o755},
	}
	for path, file := range cases {
		t.Run(path, func(t *testing.T) {
			source := &memorySource{files: map[string]memoryFile{path: file}}
			checker := NewChecker(source)
			checker.now = func() time.Time { return time.Date(2026, 8, 19, 0, 0, 0, 0, time.UTC) }
			report, err := checker.Check(context.Background(), Request{Root: "ignored", Policy: validPolicy()})
			requireCode(t, err, CodeDenied)
			if report.Findings[0].Class != "script" {
				t.Fatalf("class=%q", report.Findings[0].Class)
			}
		})
	}
}

func TestCheckerExceptionLifecycle(t *testing.T) {
	data := lineData(301)
	base := validException("scripts/legacy.sh", "script")
	base.ContentSHA256 = digestBytes(data)
	base.ApprovedMaxPhysicalLines = 800
	for name, configure := range map[string]func(*Exception, *string){
		"inclusive_expiry": func(_ *Exception, date *string) { *date = "2026-08-19" },
		"future_expiry":    func(value *Exception, date *string) { value.ExpiresOn = "2026-08-20"; *date = "2026-08-19" },
	} {
		t.Run(name, func(t *testing.T) {
			exception := base
			date := "2026-08-19"
			configure(&exception, &date)
			policy := validPolicy()
			policy.Exceptions = []Exception{exception}
			report, err := runMemoryCheck(t, map[string][]byte{exception.Path: data}, policy, date)
			requirePassed(t, report, err)
			if report.Counts.Exceptions != 1 || report.Findings[0].Reason != "approved_exception" {
				t.Fatalf("exception report=%+v", report)
			}
		})
	}
	for name, mutate := range map[string]func(*Exception, *map[string][]byte, *string){
		"expired": func(value *Exception, _ *map[string][]byte, date *string) { *date = "2026-08-20" },
		"stale": func(value *Exception, files *map[string][]byte, _ *string) {
			(*files)[value.Path] = lineData(300)
			value.ContentSHA256 = digestBytes((*files)[value.Path])
		},
		"digest": func(value *Exception, _ *map[string][]byte, _ *string) { value.ContentSHA256 = strings.Repeat("b", 64) },
		"approved_max": func(value *Exception, files *map[string][]byte, _ *string) {
			(*files)[value.Path] = lineData(700)
			value.ContentSHA256 = digestBytes((*files)[value.Path])
			value.ApprovedMaxPhysicalLines = 600
		},
		"missing": func(value *Exception, files *map[string][]byte, _ *string) {
			*files = map[string][]byte{"docs/safe.md": []byte("safe\n")}
		},
	} {
		t.Run(name, func(t *testing.T) {
			exception := base
			files := map[string][]byte{exception.Path: data}
			date := "2026-08-19"
			mutate(&exception, &files, &date)
			policy := validPolicy()
			policy.Exceptions = []Exception{exception}
			_, err := runMemoryCheck(t, files, policy, date)
			requireCode(t, err, CodeDenied)
		})
	}
}

func TestCheckerGeneratedAndSchemaExceptions(t *testing.T) {
	for name, fixture := range map[string][2]string{
		"generated": {"internal/generated.go", "// "},
		"fixture":   {"testdata/fixtures/large.txt", "# "},
	} {
		t.Run(name, func(t *testing.T) {
			data := headerData(801, fixture[1], "coh-generator")
			exception := validException(fixture[0], map[bool]string{true: "generated", false: "large_fixture"}[name == "generated"])
			exception.Generator = "coh-generator"
			exception.ContentSHA256 = digestBytes(data)
			exception.ApprovedMaxPhysicalLines = 900
			policy := validPolicy()
			policy.Exceptions = []Exception{exception}
			report, err := runMemoryCheck(t, map[string][]byte{exception.Path: data}, policy, "2026-08-19")
			requirePassed(t, report, err)
		})
	}
	jsonData := []byte("{\n  \"$comment\": \"Code generated by schema-tool; DO NOT EDIT.\",\n" + strings.Repeat("  \"x\": 1,\n", 799) + "  \"z\": 1\n}\n")
	exception := validException("contracts/example.schema.json", "schema")
	exception.Generator = "schema-tool"
	exception.ContentSHA256 = digestBytes(jsonData)
	exception.ApprovedMaxPhysicalLines = 900
	policy := validPolicy()
	policy.Exceptions = []Exception{exception}
	report, err := runMemoryCheck(t, map[string][]byte{exception.Path: jsonData}, policy, "2026-08-19")
	requirePassed(t, report, err)
}

func TestCheckerRejectsWrongExceptionClassAndOversizedScript(t *testing.T) {
	for _, test := range []struct {
		name, path, category string
		lines                int
	}{
		{"vendor_on_script", "vendor/legacy.sh", "vendor", 400},
		{"script_on_source", "internal/legacy.go", "script", 801},
		{"script_above_hard", "scripts/legacy.sh", "script", 801},
	} {
		t.Run(test.name, func(t *testing.T) {
			data := lineData(test.lines)
			exception := validException(test.path, test.category)
			exception.ContentSHA256 = digestBytes(data)
			if test.category == "script" {
				exception.ApprovedMaxPhysicalLines = 800
			}
			policy := validPolicy()
			policy.Exceptions = []Exception{exception}
			_, err := runMemoryCheck(t, map[string][]byte{test.path: data}, policy, "2026-08-19")
			requireCode(t, err, CodeDenied)
		})
	}
}

func TestCheckerRetainedReasonsProduceVerifiableReports(t *testing.T) {
	type scenario struct {
		files  map[string][]byte
		policy Policy
		reason string
	}
	makeException := func(path, category string, data []byte) (Policy, Exception) {
		exception := validException(path, category)
		exception.ContentSHA256 = digestBytes(data)
		policy := validPolicy()
		policy.Exceptions = []Exception{exception}
		return policy, exception
	}

	script301 := lineData(301)
	approvedPolicy, _ := makeException("scripts/approved.sh", "script", script301)
	expiredPolicy, expired := makeException("scripts/expired.sh", "script", script301)
	expired.ExpiresOn = "2026-08-18"
	expiredPolicy.Exceptions[0] = expired
	staleData := lineData(300)
	stalePolicy, _ := makeException("scripts/stale.sh", "script", staleData)
	digestPolicy, digestException := makeException("scripts/digest.sh", "script", script301)
	digestException.ContentSHA256 = strings.Repeat("b", 64)
	digestPolicy.Exceptions[0] = digestException
	maxData := lineData(700)
	maxPolicy, maxException := makeException("scripts/max.sh", "script", maxData)
	maxException.ApprovedMaxPhysicalLines = 600
	maxPolicy.Exceptions[0] = maxException
	wrongClassData := headerData(801, "# ", "coh-test-generator")
	wrongClassPolicy, _ := makeException("docs/vendor-long.md", "vendor", wrongClassData)
	headerDataMissing := lineData(801)
	headerPolicy, _ := makeException("contracts/missing.schema.json", "schema", headerDataMissing)
	binaryData := []byte{0xff, 0x00}
	binaryPolicy, _ := makeException("assets/binary.bin", "generated", binaryData)
	missingPolicy, _ := makeException("scripts/missing.sh", "script", script301)

	scenarios := map[string]scenario{
		"warning_threshold":                  {map[string][]byte{"docs/warning.md": lineData(501)}, validPolicy(), "warning_threshold"},
		"script_limit":                       {map[string][]byte{"scripts/denied.sh": script301}, validPolicy(), "script_limit"},
		"production_hard_limit":              {map[string][]byte{"internal/large.go": lineData(801)}, validPolicy(), "production_hard_limit"},
		"governed_asset_hard_limit":          {map[string][]byte{"contracts/large.schema.json": lineData(801)}, validPolicy(), "governed_asset_hard_limit"},
		"classified_binary_input":            {map[string][]byte{"assets/binary.bin": binaryData}, binaryPolicy, "classified_binary_input"},
		"approved_exception":                 {map[string][]byte{"scripts/approved.sh": script301}, approvedPolicy, "approved_exception"},
		"exception_expired":                  {map[string][]byte{"scripts/expired.sh": script301}, expiredPolicy, "exception_expired"},
		"exception_stale_below_limit":        {map[string][]byte{"scripts/stale.sh": staleData}, stalePolicy, "exception_stale_below_limit"},
		"exception_content_digest_mismatch":  {map[string][]byte{"scripts/digest.sh": script301}, digestPolicy, "exception_content_digest_mismatch"},
		"exception_approved_max_exceeded":    {map[string][]byte{"scripts/max.sh": maxData}, maxPolicy, "exception_approved_max_exceeded"},
		"exception_class_mismatch":           {map[string][]byte{"docs/vendor-long.md": wrongClassData}, wrongClassPolicy, "exception_class_mismatch"},
		"exception_generated_header_missing": {map[string][]byte{"contracts/missing.schema.json": headerDataMissing}, headerPolicy, "exception_generated_header_missing"},
		"exception_target_missing":           {map[string][]byte{"docs/safe.md": []byte("safe\n")}, missingPolicy, "exception_target_missing"},
	}
	for name, test := range scenarios {
		t.Run(name, func(t *testing.T) {
			report, err := runMemoryCheck(t, test.files, test.policy, "2026-08-19")
			if test.reason == "warning_threshold" || test.reason == "approved_exception" {
				requirePassed(t, report, err)
			} else {
				requireCode(t, err, CodeDenied)
			}
			if len(report.Findings) != 1 || report.Findings[0].Reason != test.reason {
				t.Fatalf("findings=%+v", report.Findings)
			}
			path := filepath.Join(t.TempDir(), "report.json")
			if err := WriteReportAtomic(path, &report); err != nil {
				t.Fatalf("WriteReportAtomic() error = %v", err)
			}
			if _, err := ReadAndVerifyReport(path); err != nil {
				t.Fatalf("ReadAndVerifyReport() error = %v", err)
			}
		})
	}
}
