package filesize

import (
	"bytes"
	"encoding/json"
	"path/filepath"
	"strings"
	"unicode/utf8"
)

var scriptExtensions = map[string]bool{
	".sh": true, ".bash": true, ".zsh": true, ".py": true, ".rb": true,
	".pl": true, ".ps1": true, ".cmd": true, ".bat": true, ".sql": true,
}

var productionExtensions = map[string]bool{
	".c": true, ".cc": true, ".cpp": true, ".cs": true, ".go": true,
	".h": true, ".hpp": true, ".java": true, ".js": true, ".jsx": true,
	".kt": true, ".kts": true, ".m": true, ".mm": true, ".rs": true,
	".swift": true, ".ts": true, ".tsx": true,
}

func classify(path string, mode uint32, data []byte) string {
	lower := strings.ToLower(path)
	base := filepath.Base(path)
	extension := strings.ToLower(filepath.Ext(base))
	if strings.HasPrefix(path, "scripts/") || strings.HasPrefix(path, ".github/workflows/") ||
		pathSegment(lower, "migrations") || strings.HasPrefix(base, "Dockerfile") ||
		base == "Makefile" || strings.HasPrefix(base, "Taskfile") || scriptExtensions[extension] ||
		mode&0o111 != 0 && bytes.HasPrefix(data, []byte("#!")) {
		return "script"
	}
	if productionExtensions[extension] && !strings.HasSuffix(lower, "_test.go") &&
		!pathSegment(lower, "testdata") && !pathSegment(lower, "fixtures") &&
		!strings.HasPrefix(lower, "tests/") {
		return "production"
	}
	return "other"
}

func physicalLines(data []byte) int {
	if len(data) == 0 {
		return 0
	}
	lines := bytes.Count(data, []byte{'\n'})
	if data[len(data)-1] != '\n' {
		lines++
	}
	return lines
}

func binaryContent(data []byte) bool {
	return !utf8.Valid(data) || bytes.IndexByte(data, 0) >= 0
}

func pathSegment(path, segment string) bool {
	path = "/" + strings.Trim(path, "/") + "/"
	return strings.Contains(path, "/"+segment+"/")
}

func exceptionClassMatches(exception Exception, path, class string, data []byte) bool {
	if class == "script" {
		return exception.Category == "script"
	}
	if exception.Category == "script" {
		return false
	}
	switch exception.Category {
	case "generated":
		return true
	case "vendor":
		return pathSegment(path, "vendor") || pathSegment(path, "third_party")
	case "schema":
		return strings.HasSuffix(path, ".schema.json") || pathSegment(path, "schema") || pathSegment(path, "schemas")
	case "migration_data":
		return pathSegment(path, "migration_data")
	case "large_fixture":
		return pathSegment(path, "fixture") || pathSegment(path, "fixtures") || pathSegment(path, "testdata")
	default:
		return false
	}
}

func generatedHeader(data []byte, generator string) bool {
	actual, ok := generatedHeaderGenerator(data)
	return ok && actual == generator
}

func generatedHeaderGenerator(data []byte) (string, bool) {
	lines := bytes.SplitN(data, []byte{'\n'}, 6)
	if len(lines) > 5 {
		lines = lines[:5]
	}
	for _, raw := range lines {
		line := strings.TrimSpace(strings.TrimSuffix(string(raw), "\r"))
		if strings.HasPrefix(line, `"$comment": `) {
			encoded := strings.TrimSuffix(strings.TrimPrefix(line, `"$comment": `), ",")
			var decoded string
			if json.Unmarshal([]byte(encoded), &decoded) != nil {
				continue
			}
			line = decoded
		} else {
			for _, prefix := range []string{"// ", "# ", "-- ", "/* ", "* "} {
				if strings.HasPrefix(line, prefix) {
					line = strings.TrimPrefix(line, prefix)
					break
				}
			}
			line = strings.TrimSuffix(line, " */")
		}
		const prefix = "Code generated by "
		const suffix = "; DO NOT EDIT."
		if strings.HasPrefix(line, prefix) && strings.HasSuffix(line, suffix) {
			generator := strings.TrimSuffix(strings.TrimPrefix(line, prefix), suffix)
			if normalizedBounded(generator, 1, 128) {
				return generator, true
			}
		}
	}
	return "", false
}

func governedAssetCandidate(path string, data []byte) bool {
	lower := strings.ToLower(path)
	if pathSegment(lower, "vendor") || pathSegment(lower, "third_party") ||
		pathSegment(lower, "schema") || pathSegment(lower, "schemas") ||
		pathSegment(lower, "migration_data") || pathSegment(lower, "fixture") ||
		pathSegment(lower, "fixtures") || pathSegment(lower, "testdata") ||
		strings.HasSuffix(lower, ".schema.json") {
		return true
	}
	_, generated := generatedHeaderGenerator(data)
	return generated
}
