package filesize

import (
	"context"
	"encoding/json"
	"os"
	"slices"
	"strings"
	"sync"
	"testing"
	"time"
)

type memoryFile struct {
	data []byte
	mode os.FileMode
}

type memorySource struct {
	mu            sync.Mutex
	files         map[string]memoryFile
	snapshotCount int
	readHook      func(context.Context, FileRecord) ([]byte, error)
	snapshotHook  func(int, Snapshot) (Snapshot, error)
}

func newMemorySource(files map[string][]byte) *memorySource {
	values := make(map[string]memoryFile, len(files))
	for path, data := range files {
		values[path] = memoryFile{data: slices.Clone(data), mode: 0o644}
	}
	return &memorySource{files: values}
}

func (source *memorySource) Snapshot(ctx context.Context, _ string) (Snapshot, error) {
	if err := ctx.Err(); err != nil {
		return Snapshot{}, contextError(err, "source")
	}
	source.mu.Lock()
	defer source.mu.Unlock()
	paths := make([]string, 0, len(source.files))
	for path := range source.files {
		paths = append(paths, path)
	}
	slices.Sort(paths)
	records := make([]FileRecord, 0, len(paths))
	for _, path := range paths {
		file := source.files[path]
		records = append(records, FileRecord{
			Path: path, Length: int64(len(file.data)), Executable: file.mode&0o111 != 0, Mode: uint32(file.mode),
			SHA256: digestBytes(file.data), Identity: "memory:" + digestBytes([]byte(path)),
		})
	}
	canonical, _ := json.Marshal(records)
	snapshot := Snapshot{
		Digest: digestBytes(canonical), FileCount: len(records), Records: records,
		VCSRevision: strings.Repeat("a", 40), VCSModified: false,
	}
	source.snapshotCount++
	if source.snapshotHook != nil {
		return source.snapshotHook(source.snapshotCount, snapshot)
	}
	return snapshot, nil
}

func (source *memorySource) Read(ctx context.Context, _ string, record FileRecord) ([]byte, error) {
	if err := ctx.Err(); err != nil {
		return nil, contextError(err, "source."+record.Path)
	}
	if source.readHook != nil {
		return source.readHook(ctx, record)
	}
	source.mu.Lock()
	defer source.mu.Unlock()
	file, ok := source.files[record.Path]
	if !ok {
		return nil, contractError(CodeDenied, "source."+record.Path, "file is missing", nil)
	}
	return slices.Clone(file.data), nil
}

func runMemoryCheck(t *testing.T, files map[string][]byte, policy Policy, date string) (Report, error) {
	t.Helper()
	parsed, err := parseDate(date)
	if err != nil {
		t.Fatalf("parseDate(%q) error = %v", date, err)
	}
	checker := NewChecker(newMemorySource(files))
	checker.now = func() time.Time { return parsed }
	return checker.Check(context.Background(), Request{Root: "ignored", Policy: policy})
}

func lineData(lines int) []byte {
	return []byte(strings.Repeat("x\n", lines))
}

func headerData(lines int, prefix, generator string) []byte {
	if lines < 1 {
		return nil
	}
	return []byte(prefix + "Code generated by " + generator + "; DO NOT EDIT.\n" + strings.Repeat("x\n", lines-1))
}

func requireCode(t *testing.T, err error, expected ErrorCode) {
	t.Helper()
	if err == nil || CodeOf(err) != expected {
		t.Fatalf("error = %v, code = %q, want %q", err, CodeOf(err), expected)
	}
}

func requirePassed(t *testing.T, report Report, err error) {
	t.Helper()
	if err != nil || report.Outcome != "passed" || report.FailureCode != "" {
		t.Fatalf("Check() outcome=%q code=%q error=%v", report.Outcome, report.FailureCode, err)
	}
}
